spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.105/sell?useSSL=false&characterEncoding=utf-8
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.0.105
    port: 6379
server:
  servlet:
    context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
# path: E:\
wechat:
  mpAppId: wx2205cb8b3b816819
  mpAppSecret: 1e73be1be27b95e96f73cc94f1d86616
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1409146202
  mchKey: c976503d34ca432c601361f969fd8d65
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sells.natappvip.cc/sell/pay/notify
  templateId:
    orderStatus: Pi296CX9498jYhnUdngFkf0n6iNmN1TkBNoq1nuIY_g
projecturl:
  wechatMpAuthorize: http://sells.natappvip.cc
  wechatOpenAuthorize: http://sells.natappvip.cc
  sell: http://sells.natappvip.cc